### ISSUE TITLE
maildir-notmuch-sync

### ISSUE THREAD

**Issue by timoc** [mturquette/ghar-email#2]
Does this invalidate your need for this script?
http://www.offlineimap.org/doc/use_cases.html#sync-from-gmail-to-a-local-maildir-with-labels

**Comment by mturquette** [comment]
No, because I use notmuch for fast email indexing and searching. Editing the mail headers after the mail is indexed by the database is problematic. In particular, this snippet from your link:

```
Note that if you need to change the label header after the labels have already
been synced, you will have to change the header manually on all messages,
otherwise offlineimap will not pick up the labels under the old header.
```

I do add and remove notmuch tags/Gmail Labels on the client side, which would mean editing the message headers, which is a no-go for notmuch users if I understand correctly.

maildir-notmuch-sync instead uses the weird Gmail imap-folders-as-labels mechanism to achieve the same thing, with no manual editing of the headers necessary.
