### ISSUE TITLE
Problems running this script in the background while modifying emails

### ISSUE THREAD

**Issue by david-sitsky** [mturquette/ghar-email#5]
Like your blog post, I have configured this script to run using the offlineimap pre/post hooks running regularly in the background.  However I have seen situations where I want to "archive" an email from Inbox, so I removed the tag -Inbox from it but right after I have done that, this script just happened to runs in "post" mode (pre mode ran just before I did my tag change and the offlineimap sync takes a while for me) and it thinks there is now an email existing in the Inbox folder without the Inbox tag, so it re-adds the Inbox again!

It seems like this race condition is expected really as described here: https://notmuchmail.org/pipermail/notmuch/2012/012414.html.

Does this mean it is best to manually run offlineimap when no mail manipulations are being done?  Or is there another way?

**Comment by mturquette** [comment]
Correct, the easy way to avoid the race condition is to not touch the tags during the update.

It might be interesting to see if there is a way to create a critical section that prevents tagging operations whenever offlineimap is running, including the pre/post hooks.

If your MUA is the trigger for pulling from imap/gmail then you can put the critical section in your mua, but if you're like me and do it via cron job, then the problem is a bit harder to solve.

I only pull every 15 minutes, so reducing your frequency of imap pulls might help reduce the number of times this issue bites you.
